<?php
/**
 * Its api for order
 *
 * @since: 12/07/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos\Api\V1
 */

namespace VitePos_Lite\Api\V1;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use Appsbd_Lite\V5\libs\API_Data_Response;
use VitePos_Lite\Libs\API_Base;
use VitePos_Lite\Libs\POS_Order;
use VitePos_Lite\Modules\POS_Settings;

/**
 * Class pos_order_api
 *
 * @package VitePos\Api\V1
 */
class Pos_Restaurant_Api extends API_Base {

	/**
	 * The set api base is generated by appsbd
	 *
	 * @return mixed|string
	 */
	public function set_api_base() {
		return 'restaurant';
	}

	/**
	 * The routes is generated by appsbd
	 *
	 * @return mixed|void
	 */
	public function routes() {
		$this->register_rest_route( 'POST', 'sync-order-list', array( $this, 'sync_order_list' ) );
	}

	/**
	 * The set route permission is generated by appsbd
	 *
	 * @param string $route Its string.
	 *
	 * @return bool
	 */
	public function set_route_permission( $route ) {
		switch ( $route ) {
			case 'sync-order-list':
				return current_user_can( 'order-list' ) || POS_Settings::is_pos_user();
			default:
				return POS_Settings::is_pos_user();
		}

		return parent::set_route_permission( $route );
	}


	/**
	 * The order list is generated by appsbd
	 *
	 * @return \Appsbd\V1\libs\API_Response
	 */
	public function sync_order_list() {
		$response_data = new API_Data_Response();
		$args          = array(
			'status'        => array( 'vt_in_kitchen', 'vt_preparing', 'cancelled', 'vt_served', 'completed', 'vt_kitchen_deny', 'vt_ready_to_srv', 'vt_cancel_request' ),
			'limit'         => $this->get_payload( 'limit', 1000 ),
			'page'          => $this->get_payload( 'page', 1 ),
			'orderby'       => 'date',
			'order'         => 'DESC',
			'paginate'      => true,
			'vt_meta_query' => array(
				array(
					'key'     => '_is_vitepos',
					'value'   => 'Y',
					'compare' => '=',
				),

				array(
					'key'     => '_vtp_is_resto',
					'value'   => 'Y',
					'compare' => '=',
				),
				array(
					'key'     => '_vtp_outlet_id',
					'value'   => $this->get_outlet_id(),
					'compare' => '=',
				),
			),
		);
		$src_props     = $this->get_payload( 'src_by', array() );
		$sort_by_props = $this->get_payload( 'sort_by', array() );
		POS_Order::order_search_props( $args, $src_props );
		POS_Order::order_sort_param( $sort_by_props, $args );
		$orders = wc_get_orders( $args );

		$orderlist = array();
		if ( ! empty( $orders->orders ) && is_array( $orders->orders ) ) {
			foreach ( $orders->orders as $order ) {
				$order_data  = POS_Order::get_from_woo_order( $order, false, true );
				$orderlist[] = $order_data;
			}
		}

		$response_data->limit = $this->get_payload( 'limit', 1000 );
		$response_data->page  = $this->get_payload( 'page', 1 );
		if ( $response_data->set_total_records( $orders->total ) ) {
			$response_data->rowdata = $orderlist;
		}

		$this->response->set_response( true, 'Order found', $response_data );
		return $this->response->get_response();
	}
}
