<?php
/**
 * Payment Wallee Terminal Method
 *
 * @author: appsbd
 * @package VitePos_Lite\Libs
 */

namespace VitePos_Lite\Libs;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Payment_Wallee_Terminal_Method
 *
 * @package VitePos_Lite\Libs
 */
class Payment_On_Account_Method extends Payment_Method_Base {

	/**
	 * The initialize is generated by appsbd
	 */
	public function initialize() {
		$this->set_admin_name( 'on_account' );
		$this->set_admin_viewable( true );
		$this->title   = 'Debt / On Account';
		$this->icon    = 'vps vps-debt-05';
		$this->id      = 'N';
		$this->comp    = 'basic';
		$this->split   = true;
		$this->offline = false;
		$this->admin_data->is_pro = 'Y';
		$this->add_field( 'Note', 'payment_note' );
	}

	/**
	 * The set admin settings is generated by appsbd
	 */
	public function set_admin_settings() {
		$this->set_admin_title_desc(
			'Enable %{brand} Payment',
			'It will allow you to take payment using %{brand} Payment gateway, make sure you have set the %{brand} limits in %{brand} settings tab.',
			array( 'brand' => 'Debt / On Account' )
		);
	}
}
